services:
  incidents-service:
    build:
      context: ./
    container_name: "incidents-service"
    ports:
      - "8081:80"
    environment:
      DB_URL: postgres://root:root@database:5432/public